### ISSUE TITLE
ModuleNotFoundError: No module named 'dart_id.fido'

### ISSUE THREAD

**Issue by lgatto** [SlavovLab/DART-ID#2]
I would like to try `dart_id` out. I started by installing it with 
```
$ pip install git+https://github.com/SlavovLab/DART-ID --user 
```
but hit the following error
```
$ dart_id -h                                                         
Traceback (most recent call last):
  File "/home/lgatto/.local/bin/dart_id", line 7, in <module>
    from dart_id.update import main
  File "/home/lgatto/.local/lib/python3.7/site-packages/dart_id/update.py", line 14, in <module>
    from dart_id.fido.BayesianNetwork import run_internal
ModuleNotFoundError: No module named 'dart_id.fido'
```
Any help appreciated.

**Comment by blahoink** [comment]
Hi,

I forgot to include the fido directory with the installation after a recent fix. The setup should now work. You can uninstall with:

`pip uninstall dart_id`

and reinstall:

`pip install git+https://github.com/SlavovLab/DART-ID --user`

Sorry for the issue, and let me know if you run into any additional problems.
